# Generated by Django 4.0.2 on 2022-02-10 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='assets/images/avatar_hy6hxz.jpg', null=True, upload_to='images'),
        ),
    ]
